#
# Module manifest for module 'TreeQuery'
#
# Generated by: parsa
#
# Generated on: 3/22/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = '.\TreeQuery.psm1'

# Version number of this module.
ModuleVersion = '1.0.3'

# ID used to uniquely identify this module
GUID = '166abd3c-0f7f-447e-8b12-732be55bf0f0'

# Author of this module
Author = 'parsa'

# Company or vendor of this module
CompanyName = 'Unknown'

# Copyright statement for this module
Copyright = '(c) parsa. All rights reserved.'

# Description of the functionality provided by this module
Description = "TreeQuery allows you to build SOQL queries, using 'selectors', powered by `Where-Object` and Powershell. Use TreeQuery when you don't know what query you want, don't know how to write it properly, or just don't feel like writing tens of hundreds of queries (all with the correct fields, references, child relationships, etc)."

# Export lists
FunctionsToExport = '*'
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'

# List of all files packaged with this module
FileList = @(
    'TreeQuery.psm1',
    'SOQLBuilder.psm1',
    'SOQL.psm1',
    'Invoke-SfCli.ps1'
)

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{
    PSData = @{ }
}

# HelpInfo URI of this module
HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
DefaultCommandPrefix = 'https://github.com/parsam97/TreeQuery.git'
}
